// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx ./prisma/seed.ts",
  },
  datasource: {
    // Produção usa uma conta sem BYPASSRLS no aplicativo e uma conta
    // administrativa separada exclusivamente para aplicar migrations.
    url: process.env["MIGRATION_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
