import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Compass, HeartHandshake, Lightbulb, ShieldCheck, Target } from "lucide-react";

export const metadata: Metadata = { title: "Nossa história", description: "Conheça a visão que deu origem ao ERP O Prestador." };

const values = [
  { icon: Compass, title: "Clareza", text: "Informação organizada para que cada pessoa saiba o que fazer e por quê." },
  { icon: Lightbulb, title: "Simplicidade", text: "Tecnologia robusta com uma experiência direta para a rotina real." },
  { icon: HeartHandshake, title: "Parceria", text: "Evolução construída perto de quem vende, executa e administra serviços." },
  { icon: ShieldCheck, title: "Confiança", text: "Controle, segurança e rastreabilidade para decisões importantes." },
];

export default function HistoriaPage() {
  return <main>
    <section className="overflow-hidden bg-[#0b1f33] text-white"><div className="mx-auto grid min-h-[600px] max-w-[1240px] items-center gap-14 px-5 py-20 lg:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-blue-300">Nossa história</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-[-.05em] sm:text-5xl">O trabalho de quem presta serviço merece uma gestão à altura.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-300">O Prestador nasceu de uma constatação simples: empresas excelentes tecnicamente ainda perdiam tempo, margem e oportunidades porque suas informações estavam espalhadas.</p><Link href="/demonstracao" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#155eef] px-6 py-3.5 text-sm font-black">Conhecer a plataforma <ArrowRight size={16}/></Link></div><div className="relative rounded-3xl border border-white/10 bg-white/[.05] p-8 sm:p-10"><Target size={34} className="text-blue-300"/><blockquote className="mt-6 text-2xl font-black leading-9">“Conectar cada etapa da empresa para transformar esforço em crescimento controlado.”</blockquote><p className="mt-5 text-sm leading-6 text-slate-400">Essa é a ideia que orienta cada módulo, tela e melhoria do produto.</p></div></div></section>
    <section className="mx-auto max-w-[1100px] px-5 py-24"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#155eef]">Por que existimos</p><h2 className="mt-4 text-3xl font-black tracking-tight">Para devolver tempo e controle a quem faz a operação acontecer.</h2></div><div className="space-y-5 text-base leading-8 text-slate-600"><p>O orçamento começa em uma conversa. Depois vêm agenda, equipe, materiais, execução, relatório, nota e recebimento. Quando cada etapa vive em uma planilha ou aplicativo diferente, a empresa cresce com retrabalho.</p><p>Construímos O Prestador para unir esse caminho. A proposta vira ordem de serviço; a execução gera histórico; materiais impactam custos; o serviço chega ao financeiro com rastreabilidade.</p><p>O resultado não é apenas digitalização. É uma operação que aprende, mede e melhora continuamente.</p></div></div></section>
    <section className="bg-[#eff6ff]"><div className="mx-auto max-w-[1240px] px-5 py-20"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#155eef]">O que nos orienta</p><h2 className="mt-4 text-3xl font-black">Princípios presentes no produto e no atendimento.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{values.map(({icon: Icon,title,text}) => <article key={title} className="rounded-2xl border border-blue-100 bg-white p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#155eef]"><Icon size={20}/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-[1100px] px-5 py-24"><div className="grid items-center gap-12 lg:grid-cols-2"><div><h2 className="text-3xl font-black tracking-tight">Uma plataforma feita para evoluir junto.</h2><p className="mt-4 text-sm leading-7 text-slate-600">Escutamos a rotina das equipes e transformamos desafios recorrentes em fluxos mais claros.</p><div className="mt-6 space-y-3">{["Menos retrabalho entre comercial e operação", "Mais visibilidade de custos e resultados", "Histórico confiável para clientes e gestores", "Processos preparados para crescer"].map(item => <p key={item} className="flex gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 size={17} className="shrink-0 text-[#12b76a]"/>{item}</p>)}</div></div><div className="rounded-3xl bg-[#0b1f33] p-8 text-white sm:p-10"><p className="text-sm leading-7 text-slate-300">Se sua empresa precisa vender melhor, executar com padrão e entender onde ganha ou perde dinheiro, queremos conhecer sua operação.</p><Link href="/contato" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-black text-[#0b1f33]">Falar com nossa equipe <ArrowRight size={15}/></Link></div></div></section>
  </main>;
}
