import Link from "next/link";
import { ArrowRight, CalendarCheck, CircleDollarSign, ClipboardCheck, LockKeyhole, Smartphone, Wrench } from "lucide-react";
import { ProviderHeader } from "@/components/provider-portal/ProviderHeader";

export default function ProviderLandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#070809] text-white">
    <ProviderHeader />
    <section className="relative border-b border-white/10 px-5 py-20 lg:py-28"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,rgba(37,99,235,.16),transparent_30rem),linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] [background-size:auto,52px_52px,52px_52px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><span className="inline-flex rounded-full border border-[#155eef]/30 bg-[#155eef]/10 px-4 py-2 text-[9px] font-black uppercase tracking-[.24em] text-[#e9c950]">Rede de parceiros Nexus</span><h1 className="mt-7 max-w-3xl text-4xl font-black leading-[1.03] tracking-[-.05em] sm:text-6xl">Seus serviços, OS e pagamentos em <span className="text-[#155eef]">um só lugar.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-zinc-400">O Portal do Prestador conecta sua equipe à operação Nexus. Consulte trabalhos liberados, acompanhe datas, informe a execução e veja os pagamentos com transparência.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/portal/prestador/cadastro" className="inline-flex items-center gap-2 rounded-xl bg-[#155eef] px-6 py-3 text-sm font-black text-black hover:bg-[#ebc94a]">Cadastrar minha empresa <ArrowRight size={17}/></Link><Link href="/portal/prestador/login" className="rounded-xl border border-white/15 bg-white/5 px-6 py-3 text-sm font-bold hover:bg-white/10">Já tenho acesso</Link></div></div><div className="rounded-[32px] border border-[#155eef]/25 bg-[#111318] p-5 shadow-[0_35px_100px_rgba(0,0,0,.55)]"><div className="rounded-[24px] border border-white/8 bg-[#0b0d11] p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#155eef]">Painel operacional</p><p className="mt-2 text-xl font-black">Bom dia, parceiro</p></div><Wrench className="text-[#155eef]"/></div><div className="mt-7 grid grid-cols-2 gap-3">{[["3","Serviços pendentes"],["1","Em execução"],["R$ 4.850","A receber"],["2","Pagamentos liberados"]].map(([value,label])=><div key={label} className="rounded-2xl border border-white/8 bg-white/[.035] p-4"><p className="text-xl font-black text-[#60a5fa]">{value}</p><p className="mt-1 text-[10px] text-zinc-500">{label}</p></div>)}</div><div className="mt-4 rounded-2xl border border-white/8 p-4"><p className="text-xs font-bold">OS-2026-0042 · Manutenção elétrica</p><p className="mt-2 text-[10px] text-zinc-500">Agendada para 18/08 · Copacabana/RJ</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full w-2/3 rounded-full bg-[#155eef]"/></div></div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#155eef]">Tudo conectado</p><h2 className="mt-3 text-3xl font-black">Mais controle. Menos mensagens dispersas.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[[ClipboardCheck,"OS organizadas","Veja cliente, serviço, status e informações necessárias para executar."],[CalendarCheck,"Agenda clara","Acompanhe datas programadas e o que ainda precisa ser iniciado."],[CircleDollarSign,"Pagamentos","Consulte valores contratados, liberações, vencimentos e pagamentos."],[Smartphone,"Acesso móvel","Use no celular durante o atendimento, sem instalar sistemas complexos."],[LockKeyhole,"Dados protegidos","Cada prestador acessa somente as OS vinculadas à própria empresa."],[Wrench,"Fluxo operacional","Inicie e conclua serviços mantendo a Nexus atualizada em tempo real."]].map(([Icon,title,text])=>{const ItemIcon=Icon as typeof Wrench;return <article key={String(title)} className="rounded-2xl border border-white/10 bg-[#101216] p-6"><ItemIcon className="text-[#155eef]"/><h3 className="mt-5 font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{String(text)}</p></article>})}</div></section>
    <footer className="border-t border-white/10 px-5 py-8 text-center text-[10px] text-zinc-600">© 2026 Nexus · Manutenção, obras e facilities</footer>
  </main>;
}
