"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CheckCircle2, CircleDollarSign, Clock3, Loader2, LogOut, Play, Wrench } from "lucide-react";
import { logoutProviderPortal, updateOwnProviderJob } from "@/app/actions/providerPortalActions";
import { formatCurrency, formatDate } from "@/lib/utils";

interface Job { id:string;description:string;clientName:string;osCode:string;osStatus:string;executionStatus:string;paymentStatus:string;costValue:number;scheduledDate:Date|null;paymentDueDate:Date|null;paymentDate:Date|null }
export function ProviderDashboard({data}:{data:{provider:{name:string;email:string|null;phone:string};jobs:Job[]}}){
 const router=useRouter();const[busy,setBusy]=useState("");const[filter,setFilter]=useState("TODOS");const jobs=useMemo(()=>data.jobs.filter(j=>filter==="TODOS"||j.executionStatus===filter||j.paymentStatus===filter),[data.jobs,filter]);
 const pending=data.jobs.filter(j=>!["CONCLUIDO","CANCELADO"].includes(j.executionStatus)).length;const receivable=data.jobs.filter(j=>j.paymentStatus!=="PAGO"&&j.executionStatus==="CONCLUIDO").reduce((s,j)=>s+j.costValue,0);const paid=data.jobs.filter(j=>j.paymentStatus==="PAGO").reduce((s,j)=>s+j.costValue,0);
 const update=async(id:string,status:"EXECUCAO"|"CONCLUIDO")=>{setBusy(id);const r=await updateOwnProviderJob(id,status);if(!r.success)alert(r.error);setBusy("");router.refresh();};
 return <main className="min-h-screen bg-[#08090b] text-white"><header className="border-b border-white/10 bg-[#0d0f12]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#d4af37]">Portal do prestador</p><p className="mt-1 font-black">{data.provider.name}</p></div><button onClick={async()=>{await logoutProviderPortal();router.push("/portal/prestador/login");router.refresh()}} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-zinc-400 hover:bg-white/5"><LogOut size={14}/> Sair</button></div></header>
 <div className="mx-auto max-w-7xl space-y-6 px-5 py-8"><section><h1 className="text-3xl font-black tracking-[-.04em]">Minha operação</h1><p className="mt-2 text-sm text-zinc-500">Acompanhe seus serviços e pagamentos vinculados à Nexus.</p></section><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[Wrench,"A executar",pending],[Clock3,"Em execução",data.jobs.filter(j=>j.executionStatus==="EXECUCAO").length],[CircleDollarSign,"A receber",formatCurrency(receivable)],[CheckCircle2,"Já recebido",formatCurrency(paid)]].map(([Icon,label,value])=>{const I=Icon as typeof Wrench;return <div key={String(label)} className="rounded-2xl border border-white/10 bg-[#111419] p-5"><I className="text-[#d4af37]" size={18}/><p className="mt-4 text-[9px] font-bold uppercase tracking-wider text-zinc-600">{String(label)}</p><p className="mt-1 text-xl font-black">{String(value)}</p></div>})}</section>
 <section className="overflow-hidden rounded-[24px] border border-white/10 bg-[#111419]"><div className="flex flex-col justify-between gap-3 border-b border-white/10 p-5 sm:flex-row sm:items-center"><div><h2 className="font-black">Meus serviços</h2><p className="mt-1 text-xs text-zinc-600">Valores apresentados correspondem ao combinado com a Nexus.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-white/10 bg-[#090b0e] px-4 py-2 text-xs">{["TODOS","PENDENTE","AGENDADO","EXECUCAO","CONCLUIDO","PAGO"].map(x=><option key={x}>{x}</option>)}</select></div><div className="divide-y divide-white/8">{jobs.map(j=><article key={j.id} className="grid gap-5 p-5 lg:grid-cols-[1.4fr_.75fr_.75fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-black text-[#e6c653]">{j.osCode}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-black text-zinc-400">{j.executionStatus}</span></div><h3 className="mt-3 text-sm font-bold">{j.description}</h3><p className="mt-1 text-xs text-zinc-500">Cliente: {j.clientName}</p></div><div><p className="text-[9px] font-bold uppercase text-zinc-600">Agendamento</p><p className="mt-2 text-xs font-bold">{j.scheduledDate?<><CalendarDays size={13} className="mr-1 inline text-[#d4af37]"/>{formatDate(j.scheduledDate)}</>:"A definir"}</p></div><div><p className="text-[9px] font-bold uppercase text-zinc-600">Pagamento</p><p className="mt-2 font-black">{formatCurrency(j.costValue)}</p><p className={`mt-1 text-[9px] font-black ${j.paymentStatus==="PAGO"?"text-emerald-400":"text-[#d4af37]"}`}>{j.paymentStatus}</p></div><div className="flex gap-2">{["PENDENTE","AGENDADO"].includes(j.executionStatus)&&<button disabled={busy===j.id} onClick={()=>update(j.id,"EXECUCAO")} className="flex items-center gap-2 rounded-xl border border-[#d4af37]/30 px-4 py-2 text-xs font-black text-[#e6c653]"><Play size={13}/>Iniciar</button>}{j.executionStatus==="EXECUCAO"&&<button disabled={busy===j.id} onClick={()=>update(j.id,"CONCLUIDO")} className="flex items-center gap-2 rounded-xl bg-[#d4af37] px-4 py-2 text-xs font-black text-black"><CheckCircle2 size={14}/>Concluir</button>}{busy===j.id&&<Loader2 className="animate-spin text-[#d4af37]"/>}</div></article>)}{!jobs.length&&<p className="py-16 text-center text-sm text-zinc-600">Nenhum serviço encontrado.</p>}</div></section></div></main>
}
