import { listConstructionBudgets, createConstructionBudget } from "@/app/actions/constructionBudgetActions";

export default async function ConstructionBudgetsPage() {
  const budgets = await listConstructionBudgets();
  return <main className="min-h-screen bg-zinc-50 px-4 py-8 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100 md:px-8">
    <div className="mx-auto max-w-7xl">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Engenharia e licitações</p><h1 className="mt-2 text-3xl font-black">Orçamentos de Obras</h1><p className="mt-1 text-sm text-zinc-500">Quantitativos, bases oficiais, BDI, curva ABC e cronograma físico-financeiro.</p></div><a href="#novo" className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20">Novo orçamento de obra</a></div>
      <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
        <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Orçamentos salvos</h2><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-bold dark:bg-zinc-800">{budgets.length} registros</span></div>{budgets.length === 0 ? <div className="rounded-xl border border-dashed border-zinc-300 p-10 text-center text-sm text-zinc-500">Nenhum orçamento de obra criado.</div> : <div className="space-y-3">{budgets.map((b) => <div key={b.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-zinc-200 p-4 dark:border-zinc-800"><div><p className="font-bold">{b.workName}</p><p className="mt-1 text-xs text-zinc-500">{b.code} · versão {b.version} · {b._count.items} itens</p></div><div className="text-right"><p className="font-black">R$ {Number(b.globalTotal).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</p><span className="text-[11px] font-bold text-blue-600">{b.status}</span></div></div>)}</div>}</section>
        <section id="novo" className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><h2 className="font-bold">Cadastrar obra</h2><form action={async (fd) => { "use server"; await createConstructionBudget(fd); }} className="mt-4 space-y-3"><input name="workName" required placeholder="Nome da obra *" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/><input name="contractorName" placeholder="Empresa contratada" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/><input name="technicalLead" placeholder="Responsável técnico / CREA" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/><input name="address" placeholder="Endereço da obra" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isPublic"/> Obra pública / licitação</label><input name="agency" placeholder="Órgão contratante" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/><div className="grid grid-cols-2 gap-2"><input name="modality" placeholder="Modalidade" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/><input name="procurementNumber" placeholder="Nº edital/processo" className="w-full rounded-lg border border-zinc-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"/></div><button className="w-full rounded-lg bg-blue-600 px-4 py-3 text-sm font-bold text-white">Criar orçamento</button></form></section>
      </div>
    </div>
  </main>;
}
