ALTER TABLE "Quote"
ADD COLUMN "overheadPercentage" DECIMAL(7,2) NOT NULL DEFAULT 0,
ADD COLUMN "riskPercentage" DECIMAL(7,2) NOT NULL DEFAULT 0,
ADD COLUMN "financialPercentage" DECIMAL(7,2) NOT NULL DEFAULT 0,
ADD COLUMN "profitPercentage" DECIMAL(7,2) NOT NULL DEFAULT 0,
ADD COLUMN "taxPercentage" DECIMAL(7,2) NOT NULL DEFAULT 0,
ADD COLUMN "bdiPercentage" DECIMAL(7,2) NOT NULL DEFAULT 0;

ALTER TABLE "Service"
ADD COLUMN "serviceType" TEXT NOT NULL DEFAULT 'PROPRIO',
ADD COLUMN "referenceCode" TEXT,
ADD COLUMN "materialCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "laborCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "equipmentCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "otherDirectCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "productivity" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "supplierId" TEXT;

CREATE INDEX "Service_serviceType_idx" ON "Service"("serviceType");
CREATE INDEX "Service_supplierId_idx" ON "Service"("supplierId");
ALTER TABLE "Service" ADD CONSTRAINT "Service_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE SET NULL ON UPDATE CASCADE;
