"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BookOpen, ChevronLeft, Clock3, Loader2, Pencil, Play, Plus, Search, Trash2, Video, X } from "lucide-react";
import { deleteTrainingVideoAction, getTrainingVideosAction, saveTrainingVideoAction, TrainingVideo } from "@/app/actions/trainingActions";
import { PrestadorBrand } from "@/components/brand/PrestadorBrand";

const emptyVideo = (): TrainingVideo => ({ id: crypto.randomUUID(), title: "", description: "", youtubeUrl: "", category: "Primeiros passos", duration: "", published: true, order: 0 });
function youtubeId(url: string) { try { const parsed = new URL(url); if (parsed.hostname.includes("youtu.be")) return parsed.pathname.slice(1); if (parsed.pathname.startsWith("/shorts/")) return parsed.pathname.split("/")[2]; return parsed.searchParams.get("v") || ""; } catch { return ""; } }

export default function TrainingCenter() {
  const [videos, setVideos] = useState<TrainingVideo[]>([]); const [canManage, setCanManage] = useState(false); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [category, setCategory] = useState("Todos"); const [selected, setSelected] = useState<TrainingVideo | null>(null); const [editing, setEditing] = useState<TrainingVideo | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const data = await getTrainingVideosAction(); setVideos(data.videos); setCanManage(data.canManage); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const categories = useMemo(() => ["Todos", ...Array.from(new Set(videos.map((v) => v.category)))], [videos]);
  const filtered = videos.filter((v) => (category === "Todos" || v.category === category) && `${v.title} ${v.description}`.toLowerCase().includes(query.toLowerCase()));
  const save = async () => { if (!editing) return; setSaving(true); setError(""); const result = await saveTrainingVideoAction(editing); setSaving(false); if (!result.success) return setError(result.error); setEditing(null); await load(); };
  const remove = async (id: string) => { if (!window.confirm("Excluir este treinamento?")) return; await deleteTrainingVideoAction(id); if (selected?.id === id) setSelected(null); await load(); };

  return <div className="min-h-screen bg-[#f7f9fc] text-[#0b1f33]">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-5"><Link href="/"><PrestadorBrand /></Link><div className="flex items-center gap-2"><Link href="/" className="inline-flex items-center gap-2 rounded-xl px-4 py-2 text-xs font-black text-slate-600 hover:bg-slate-100"><ChevronLeft size={14}/> Voltar ao site</Link>{canManage && <button onClick={() => setEditing(emptyVideo())} className="inline-flex items-center gap-2 rounded-xl bg-[#155eef] px-4 py-2.5 text-xs font-black text-white"><Plus size={14}/> Novo vídeo</button>}</div></div></header>
    <section className="bg-[#0b1f33] text-white"><div className="mx-auto max-w-[1240px] px-5 py-14"><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.22em] text-blue-300"><BookOpen size={14}/> Central de conhecimento</span><h1 className="mt-4 text-4xl font-black tracking-[-.045em]">Treinamentos O Prestador</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Aprenda cada etapa do ERP com vídeos rápidos e organizados por módulo.</p><div className="relative mt-8 max-w-xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar treinamento..." className="h-12 w-full rounded-xl border border-white/10 bg-white/10 pl-11 pr-4 text-sm text-white outline-none placeholder:text-slate-500 focus:border-blue-400"/></div></div></section>
    <main className="mx-auto max-w-[1240px] px-5 py-10"><div className="flex gap-2 overflow-x-auto pb-3">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-[11px] font-black ${category === item ? "bg-[#155eef] text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{item}</button>)}</div>
      {loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#155eef]"/></div> : filtered.length ? <div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map((video) => { const id = youtubeId(video.youtubeUrl); return <article key={video.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><button onClick={() => setSelected(video)} className="group relative block aspect-video w-full overflow-hidden bg-[#0d1b2a] text-white">{id && <img src={`https://i.ytimg.com/vi/${id}/hqdefault.jpg`} alt="" className="h-full w-full object-cover opacity-80 transition group-hover:scale-105"/>}<span className="absolute inset-0 grid place-items-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#155eef] shadow-xl"><Play size={20} fill="white"/></span></span>{!video.published && <span className="absolute left-3 top-3 rounded-lg bg-amber-400 px-2 py-1 text-[9px] font-black text-black">RASCUNHO</span>}</button><div className="p-5"><div className="flex items-center justify-between gap-3"><span className="text-[9px] font-black uppercase tracking-wider text-[#155eef]">{video.category}</span>{video.duration && <span className="flex items-center gap-1 text-[10px] text-slate-400"><Clock3 size={11}/>{video.duration}</span>}</div><h2 className="mt-2 font-black">{video.title}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{video.description}</p>{canManage && <div className="mt-4 flex gap-2 border-t border-slate-100 pt-3"><button onClick={() => setEditing(video)} className="inline-flex items-center gap-1 text-[10px] font-bold text-slate-500 hover:text-blue-600"><Pencil size={12}/> Editar</button><button onClick={() => void remove(video.id)} className="inline-flex items-center gap-1 text-[10px] font-bold text-slate-500 hover:text-red-600"><Trash2 size={12}/> Excluir</button></div>}</div></article>; })}</div> : <div className="mt-6 grid min-h-72 place-items-center rounded-2xl border border-dashed border-slate-300 bg-white text-center"><div><Video className="mx-auto text-slate-300" size={36}/><h2 className="mt-4 font-black">Nenhum treinamento disponível</h2><p className="mt-2 text-sm text-slate-500">{canManage ? "Clique em “Novo vídeo” para adicionar o primeiro link do YouTube." : "Novos conteúdos serão publicados em breve."}</p></div></div>}
    </main>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4" onClick={() => setSelected(null)}><div className="w-full max-w-4xl overflow-hidden rounded-2xl bg-[#0b1f33] text-white shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between p-4"><div><p className="text-[9px] font-black uppercase tracking-wider text-blue-300">{selected.category}</p><h2 className="mt-1 font-black">{selected.title}</h2></div><button onClick={() => setSelected(null)} className="rounded-xl p-2 hover:bg-white/10"><X size={18}/></button></div><div className="aspect-video bg-black"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${youtubeId(selected.youtubeUrl)}?autoplay=1`} title={selected.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/></div></div></div>}
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0b1f33]/80 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-[#155eef]">Gerenciar conteúdo</p><h2 className="mt-1 text-xl font-black">Vídeo de treinamento</h2></div><button onClick={() => setEditing(null)} className="rounded-xl p-2 hover:bg-slate-100"><X size={18}/></button></div><div className="mt-6 grid gap-4"><label className="text-xs font-bold">Título<input value={editing.title} onChange={(e) => setEditing({...editing,title:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-blue-500"/></label><label className="text-xs font-bold">Link do YouTube<input value={editing.youtubeUrl} onChange={(e) => setEditing({...editing,youtubeUrl:e.target.value})} placeholder="https://youtube.com/watch?v=..." className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-blue-500"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Categoria<input value={editing.category} onChange={(e) => setEditing({...editing,category:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-xs font-bold">Duração<input value={editing.duration} onChange={(e) => setEditing({...editing,duration:e.target.value})} placeholder="Ex: 08:30" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label></div><label className="text-xs font-bold">Descrição<textarea value={editing.description} onChange={(e) => setEditing({...editing,description:e.target.value})} rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={editing.published} onChange={(e) => setEditing({...editing,published:e.target.checked})}/> Publicado para os usuários</label>{error && <p className="text-xs font-bold text-red-600">{error}</p>}<button onClick={() => void save()} disabled={saving} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#155eef] text-sm font-black text-white disabled:opacity-60">{saving && <Loader2 size={15} className="animate-spin"/>} Salvar treinamento</button></div></div></div>}
  </div>;
}
